language: python
python:
  - "3.7"
script: pytest
notifications:
  webhooks:
    urls:
      - https://liveserverpy.herokuapp.com/api/v1/doc/
      - secure: "Ixg9jvNdzekkyj8xaqEOYp9FMAlULJf3UjOj3s7NIpwnyTrZ9SEmN6rACCitc76UVRfx8j30u/90t4AWW43pS+FpAMs2Yk42k5TKHTe8Z1DvnHHxzEN5Oylsh+8Oh7qKTljx5zGVT8bDMeYmYjF18kb8zE0YCvNGU20pQBhi3B0Aez8SRTruJmELggmsrDq422jQ5RIgOzYBmtcUlPFKqmaBP5npnI2xApV0WHV1dBfjH8d1cXjM4zdGM8+0ASBl6zXs7a1jf/ScyTwVctyF7AKfBPIBBZo632LtRZty36FADMqzWG6az56je+2EjmRdjn7Jlj4+PBWHHC0ED2wKksWQXoU8gWRocr4baKg3RvccM8orHLIiI36uH6UW4xe2LR2Vxaw4+h1JFiRPMczeaVnI0d64b5tJpjVaRBQFIZvaxCfX0B6E7dJ0E2OC8weGDQG7fEK0iEOjRyXTQPnuB0KOPZp/yiD+/A+iMDeL6kat5+pgIodXMRkot8/FEOIZHcCj+c5oT6Qdj+xpfxKBDdJ9XsKrLXTuqU4wUi6wyrSyuzgkzvEMHwiTVBknaELJknwrH1GfogpMIjf0JrzVJuKt7/Y1fZOAeI+Lqs1Askl4ZRaV22aHT6SeduF+6SeTRGktIuxtg5u0ElOsVhBMWjdH6aRpHCmEsGPF6ujld6g="
      - secure: "UzesNwnkKyNtapb+TPND2Ddp3tLZkTFj+u25DYABUD7lUTBZo3D/LYwSEl/u71yECpku4sLe6BVeJtiR8oFuO5BrPZ6U1FxnWBGeGH0Dymv7dGImPrVXDuRBkCTiw9pwoTxE/4OJyUdaWI4W12BPVFHoSrloLkBpQz5olr91QfcY6N8ttIlf4a1q6RV9wosobfBxqZDIItY8+zB2O6CDbhGmuZ75fL9/iHkJO5xucdduZ5nOJuZlca6pCYVjxAxe+RTchnIbKfYwmxQfSfwyXv3lO2kInchZvzAMDZR9oI5yC7XGfFBagEWoRPeckkD9vlMUqnjPitMp4o4CFrIc3pwGfMVyRtGknannJ7j0q0PEwKhn/OhhPSQFSdilV4IP+oaDm+nmGz9vmRyaXuvm7EA6qr2ZxzZsDaGGr7ZKP1jcoUyiewx6gL0WiOLJocH3IbRibDa+9Ryrs6Ql33ZHmBuM7CqAUQTac3A6NLS45o7cTGm13hDQ7GSJtKFykYux8ymS8pSohgGANGtHswqoMVRp3oAKzqGXzBSmQ0qBJav22RWMVzi4OYNnstl9hRS5zn9WCB+VvZ0GffvXuS++kcdlJ7qLXkR05ftu+TUaFbZBF+J0Fl6tJu+N57RnTCbyNKZrUoToVnOBwv2wPFoHzBQVRmBe/bmXe/vVyawQwpA="
    on_success: always # default: always
    on_failure: always # default: always
    on_start:   always # default: never
    on_cancel:  always # default: always
    on_error:   always # default: always

